version: '3'

services: 
    app_database:
        image:  'mongo:latest'
        container_name: 'app_database'
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=fajrul
            - MONGO_INITDB_ROOT_PASSWORD=aulia
        volumes: 
            - ./mongo-init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - '27017:27017'
        restart: always

    app_manager:
        image: "mongo-express:latest" 
        container_name: 'app_manager'
        restart: always
        depends_on:
            - app_database
        environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=fajrul
         - ME_CONFIG_MONGODB_ADMINPASSWORD=aulia
         - ME_CONFIG_MONGODB_SERVER=app_database
         - ME_CONFIG_BASICAUTH_USERNAME=admin
         - ME_CONFIG_BASICAUTH_PASSWORD=admin
        ports:
         - '8081:8081'