version: '3'

services: 

    app_backend:
        image: faaa/backend 
        ports:
          - "8080:8080"
        depends_on:
          - app_database
        environment:
          DATABASE_URL: postgres://todoapp@postgres/todos

    app_database:
        image:  'mongo:latest'
        container_name: 'app_database'
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: oort
            MONGO_INITDB_DATABASE: fajruldb
        command: mongod
        volumes: 
            - ./mongo-entrypoint:/docker-entrypoint-initdb.d/
        ports:
            - '27017:27017'
        restart: always

    app_manager:
        image: "mongo-express:latest" 
        container_name: 'app_manager'
        restart: always
        depends_on:
            - app_database
        environment:
         - ME_CONFIG_MONGODB_ADMINUSERNAME=root
         - ME_CONFIG_MONGODB_ADMINPASSWORD=oort
         - ME_CONFIG_MONGODB_SERVER=app_database
         - ME_CONFIG_BASICAUTH_USERNAME=admin
         - ME_CONFIG_BASICAUTH_PASSWORD=nomad
        ports:
         - '8081:8081'